// A page that sets its own `openGraph` replaces the root one, including the
// image generated by app/opengraph-image.tsx, so pages add this back in.
export const OG_IMAGES = [
  {
    url: '/opengraph-image',
    width: 1200,
    height: 630,
    alt: 'Khoironi Kurnia Syah, Product Engineer'
  }
];
